apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-wf-cm-v2
  labels:
    workflow-name: "simple-workflow"
    workflow-version: "2"
data:
  workflow.json: |
    {
      "name": "simple-workflow",
      "version": "2",
      "states": [
        {
          "name": "test-state",
          "type": "OPERATION",
          "start": true,
          "action-mode": "SEQUENTIAL",
          "actions": [
            {
              "function": {
                "name": "testFunction",
                "type": "someType",
                "parameters": {
                  "one": "1",
                  "two": "two"
                }
              },
              "timeout": 5
            }
          ],
          "next-state": "end-state"
        },
        {
          "name": "end-state",
          "type": "END"
        }
      ]
    }
