apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Hot Rod's port.
  labels:
    application: infinispan-server
  name: infinispan-server-hotrod
spec:
  ports:
  - port: 11222
    targetPort: 11222
  selector:
    deploymentConfig: infinispan-server