apiVersion: app.kiegroup.org/v1alpha1
kind: Workflow
metadata:
  name: example-workflow
spec:
  definition:
    states:
      - start: true
        type: OPERATION
        name: Calculate user is an adult
        action-mode: SEQUENTIAL
        actions:
          - function:
              name: Set adult
              type: Rest
              parameters:
                url: http://test-services:8080/age
        next-state: Only adults allowed
      - name: Only adults allowed
        type: SWITCH
        choices:
          - path: $.adult
            value: "true"
            operator: EQ
            next-state: Log allowed
        default: Log not allowed
      - name: Log allowed
        type: OPERATION
        action-mode: SEQUENTIAL
        next-state: Allow access
        actions:
          - function:
              name: Log user is adult
              type: Log
              parameters:
                field: $.adult
                level: INFO
      - name: Log not allowed
        type: OPERATION
        action-mode: SEQUENTIAL
        next-state: Access not allowed
        actions:
          - function:
              name: User is NOT adult
              type: Log
              parameters:
                field: $.name
                level: ERROR
      - name: Allow access
        type: END
        status: SUCCESS
      - name: Access not allowed
        type: END
        status: FAILURE
