apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflows.app.kiegroup.org
spec:
  group: app.kiegroup.org
  names:
    kind: Workflow
    listKind: WorkflowList
    plural: workflows
    singular: workflow
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            definition:
              properties:
                metadata:
                  additionalProperties:
                    type: string
                  type: object
                states:
                  items:
                    properties:
                      actions:
                        items:
                          properties:
                            filter:
                              properties:
                                metadata:
                                  additionalProperties:
                                    type: string
                                  type: object
                              type: object
                            function:
                              properties:
                                metadata:
                                  additionalProperties:
                                    type: string
                                  type: object
                                name:
                                  type: string
                              required:
                              - name
                              type: object
                            metadata:
                              additionalProperties:
                                type: string
                              type: object
                          required:
                          - function
                          type: object
                        type: array
                      choices:
                        items:
                          properties:
                            metadata:
                              additionalProperties:
                                type: string
                              type: object
                            operator:
                              type: string
                            path:
                              type: string
                            value:
                              type: string
                          required:
                          - path
                          - value
                          - operator
                          type: object
                        type: array
                      filter:
                        properties:
                          metadata:
                            additionalProperties:
                              type: string
                            type: object
                        type: object
                      metadata:
                        additionalProperties:
                          type: string
                        type: object
                      name:
                        type: string
                      start:
                        type: boolean
                      type:
                        type: string
                    required:
                    - name
                    - type
                    type: object
                  type: array
              type: object
            image:
              type: string
            knative:
              type: boolean
            watch:
              type: boolean
          required:
          - definition
          type: object
        status:
          properties:
            deployments:
              properties:
                ready:
                  description: Deployments are ready to serve requests
                  items:
                    type: string
                  type: array
                starting:
                  description: Deployments are starting, may or may not succeed
                  items:
                    type: string
                  type: array
                stopped:
                  description: Deployments are not starting, unclear what next step
                    will be
                  items:
                    type: string
                  type: array
              type: object
          required:
          - deployments
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
