apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: workflow-operator
  template:
    metadata:
      labels:
        name: workflow-operator
    spec:
      serviceAccountName: workflow-operator
      containers:
        - name: workflow-operator
          image: quay.io/ruben/serverless-workflow-operator:latest
          command:
          - serverless-workflow-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "workflow-operator"
