apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-reader
rules:
- apiGroups:
    - app.kiegroup.org
  resources:
    - serverlessorchestrationapps
  verbs:
    - get
    - watch
    - list