// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerlessOrchestrationApp) DeepCopyInto(out *ServerlessOrchestrationApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerlessOrchestrationApp.
func (in *ServerlessOrchestrationApp) DeepCopy() *ServerlessOrchestrationApp {
	if in == nil {
		return nil
	}
	out := new(ServerlessOrchestrationApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServerlessOrchestrationApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerlessOrchestrationAppList) DeepCopyInto(out *ServerlessOrchestrationAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServerlessOrchestrationApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerlessOrchestrationAppList.
func (in *ServerlessOrchestrationAppList) DeepCopy() *ServerlessOrchestrationAppList {
	if in == nil {
		return nil
	}
	out := new(ServerlessOrchestrationAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServerlessOrchestrationAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerlessOrchestrationAppSpec) DeepCopyInto(out *ServerlessOrchestrationAppSpec) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]v1.ContainerPort, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerlessOrchestrationAppSpec.
func (in *ServerlessOrchestrationAppSpec) DeepCopy() *ServerlessOrchestrationAppSpec {
	if in == nil {
		return nil
	}
	out := new(ServerlessOrchestrationAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerlessOrchestrationAppStatus) DeepCopyInto(out *ServerlessOrchestrationAppStatus) {
	*out = *in
	in.Deployments.DeepCopyInto(&out.Deployments)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerlessOrchestrationAppStatus.
func (in *ServerlessOrchestrationAppStatus) DeepCopy() *ServerlessOrchestrationAppStatus {
	if in == nil {
		return nil
	}
	out := new(ServerlessOrchestrationAppStatus)
	in.DeepCopyInto(out)
	return out
}
